[package]
name = "cipher-realtime-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
cipher-types = { path = "../cipher-types", version = "^0.1.0-prealpha.10" }
serde.workspace = true
serde_json.workspace = true
