version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      rust:
        patterns: ["*"]
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    groups:
      frontend:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /infra
    schedule:
      interval: weekly
    groups:
      infrastructure:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
