import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const fixturePrefix = "cipher-live-it-";
const fixtureObjectRoot = "fixtures/";

export interface CommandResult {
  readonly exitCode: number;
  readonly stderr: string;
  readonly stdout: string;
}

export interface CommandRunner {
  run(command: ReadonlyArray<string>): CommandResult;
}

export interface LiveFixtureConfig {
  readonly accountId: string;
  readonly bucket: string;
  readonly cognitoClientId: string;
  readonly cognitoUserPoolId: string;
  readonly conversationsTable: string;
  readonly mediaTable: string;
  readonly messagesTable: string;
  readonly region: string;
  readonly stateStack: string;
  readonly usersTable: string;
}

/** One exact namespace that owns every live fixture in a run. */
export interface FixtureScope {
  readonly id: string;
  readonly namespace: string;
  objectKey(label: string): string;
  resourceId(label: string): string;
}

interface StackOutput {
  readonly OutputKey?: unknown;
  readonly OutputValue?: unknown;
}

interface StackResponse {
  readonly Stacks?: ReadonlyArray<{
    readonly Outputs?: ReadonlyArray<StackOutput>;
  }>;
}

interface DynamoGetResponse {
  readonly Item?: {
    readonly fixture_run_id?: { readonly S?: unknown };
  };
}

interface ObjectTaggingResponse {
  readonly TagSet?: ReadonlyArray<{
    readonly Key?: unknown;
    readonly Value?: unknown;
  }>;
}

/** Executes commands against the current shell environment. */
const liveRunner: CommandRunner = {
  run(command) {
    const result = Bun.spawnSync([...command], { stderr: "pipe", stdout: "pipe" });
    return {
      exitCode: result.exitCode,
      stderr: new TextDecoder().decode(result.stderr),
      stdout: new TextDecoder().decode(result.stdout),
    };
  },
};

/**
 * Parses the production values that fixture operations need.
 *
 * @param environment - Process environment to validate.
 * @returns A live-fixture configuration with no optional targets.
 */
export function loadLiveFixtureConfig(
  environment: Readonly<Record<string, string | undefined>>,
): LiveFixtureConfig {
  const required = (key: string): string => {
    const value = environment[key];
    if (value === undefined || value.length === 0 || value.trim() !== value) {
      throw new Error(`${key} must be a non-empty value without surrounding whitespace.`);
    }
    return value;
  };

  const accountId = required("CIPHER_AWS_ACCOUNT_ID");
  if (!/^\d{12}$/u.test(accountId) || accountId === "000000000000") {
    throw new Error("CIPHER_AWS_ACCOUNT_ID must name the 12-digit production account.");
  }

  const region = required("CIPHER_AWS_REGION");
  if (region !== "us-east-1") {
    throw new Error("CIPHER_AWS_REGION must be us-east-1.");
  }

  return {
    accountId,
    bucket: required("CIPHER_MEDIA_BUCKET"),
    cognitoClientId: required("CIPHER_COGNITO_CLIENT_ID"),
    cognitoUserPoolId: required("CIPHER_COGNITO_USER_POOL_ID"),
    conversationsTable: required("CIPHER_CONVERSATIONS_TABLE"),
    mediaTable: required("CIPHER_MEDIA_TABLE"),
    messagesTable: required("CIPHER_MESSAGES_TABLE"),
    region,
    stateStack: required("CIPHER_STATE_STACK"),
    usersTable: required("CIPHER_USERS_TABLE"),
  };
}

/**
 * Creates an exact, UUID-owned fixture namespace.
 *
 * @param id - Lowercase UUID v4 identifying one run.
 * @returns A scope that cannot construct broad fixture identifiers.
 */
export function createFixtureScope(id: string): FixtureScope {
  if (!isUuidV4(id)) throw new Error("Fixture run id must be a lowercase UUID v4.");
  const namespace = `${fixturePrefix}${id}`;

  const safeLabel = (label: string): string => {
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/u.test(label)) {
      throw new Error("Fixture label must use lowercase letters, digits, and single hyphens.");
    }
    return label;
  };

  return {
    id,
    namespace,
    objectKey: (label) => `${fixtureObjectRoot}${id}/${safeLabel(label)}`,
    resourceId: (label) => `${namespace}-${safeLabel(label)}`,
  };
}

/**
 * Runs the isolated Cognito, DynamoDB, and S3 fixture lifecycle.
 *
 * It only mutates names and object keys derived from a fresh UUID v4. Cleanup checks the
 * DynamoDB ownership marker and S3 object tag before deleting either resource.
 *
 * @param config - Verified production resource configuration.
 * @param runner - Command runner for AWS CLI calls.
 * @param id - Optional UUID v4 for deterministic testing; a fresh UUID is generated by default.
 */
export function runLiveFixtureCheck(
  config: LiveFixtureConfig,
  runner: CommandRunner = liveRunner,
  id = crypto.randomUUID(),
): string[] {
  const scope = createFixtureScope(id);
  assertActiveAccount(config, runner);
  assertStateOutputs(config, runner);

  const alice = fixtureUserName(scope, "alice");
  const bob = fixtureUserName(scope, "bob");
  const fixtureKey = scope.objectKey("ciphertext");
  const sentinelKey = scope.objectKey("sentinel");
  const fixtureItem = fixtureDynamoItem(scope, "record");
  const sentinelItem = sentinelDynamoItem(scope, "sentinel");
  const temporaryDirectory = mkdtempSync(join(tmpdir(), "cipher-live-fixture-"));
  const payload = join(temporaryDirectory, "ciphertext.bin");
  const createdUsers: string[] = [];
  let fixtureItemCreated = false;
  let fixtureObjectCreated = false;
  let sentinelItemCreated = false;
  let sentinelObjectCreated = false;

  try {
    writeFileSync(payload, "cipher live fixture\n");

    for (const username of [alice, bob]) {
      createFixtureUser(config, runner, scope, username);
      createdUsers.push(username);
      assertFixtureUser(config, runner, username);
    }

    putDynamoItem(config, runner, fixtureItem);
    fixtureItemCreated = true;
    putDynamoItem(config, runner, sentinelItem);
    sentinelItemCreated = true;
    assertDynamoMarker(config, runner, fixtureItem, scope.id);

    putFixtureObject(config, runner, fixtureKey, payload, scope.id);
    fixtureObjectCreated = true;
    putFixtureObject(config, runner, sentinelKey, payload);
    sentinelObjectCreated = true;
    assertObjectMarker(config, runner, fixtureKey, scope.id);

    deleteMarkedDynamoItem(config, runner, fixtureItem, scope.id);
    fixtureItemCreated = false;
    deleteMarkedObject(config, runner, fixtureKey, scope.id);
    fixtureObjectCreated = false;
    assertDynamoItemExists(config, runner, sentinelItem);
    assertObjectExists(config, runner, sentinelKey);

    return [
      `Created, checked, and removed two Cognito fixtures in ${scope.namespace}.`,
      `Created and removed only marked DynamoDB and S3 fixtures for ${scope.id}.`,
      "Verified that unmarked same-prefix sentinel resources remained untouched.",
    ];
  } finally {
    if (fixtureObjectCreated) deleteMarkedObject(config, runner, fixtureKey, scope.id);
    if (sentinelObjectCreated) deleteExactObject(config, runner, sentinelKey);
    if (fixtureItemCreated) deleteMarkedDynamoItem(config, runner, fixtureItem, scope.id);
    if (sentinelItemCreated) deleteExactDynamoItem(config, runner, sentinelItem);
    for (const username of createdUsers.reverse()) deleteExactUser(config, runner, username);
    rmSync(temporaryDirectory, { force: true, recursive: true });
  }
}

function isUuidV4(value: string): boolean {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u.test(value);
}

function aws(config: LiveFixtureConfig, ...args: string[]): string[] {
  return ["aws", ...args, "--region", config.region];
}

function run(command: ReadonlyArray<string>, runner: CommandRunner, subject: string): string {
  const result = runner.run(command);
  if (result.exitCode !== 0) {
    throw new Error(
      `${subject} failed: ${result.stderr.trim() || "AWS CLI exited unsuccessfully."}`,
    );
  }
  return result.stdout;
}

function parseJson<T>(value: string, subject: string): T {
  try {
    return JSON.parse(value) as T;
  } catch {
    throw new Error(`Could not read ${subject}.`);
  }
}

function assertActiveAccount(config: LiveFixtureConfig, runner: CommandRunner): void {
  const account = run(
    aws(config, "sts", "get-caller-identity", "--query", "Account", "--output", "text"),
    runner,
    "AWS account check",
  ).trim();
  if (account !== config.accountId)
    throw new Error("The active AWS account is not Cipher production.");
}

function assertStateOutputs(config: LiveFixtureConfig, runner: CommandRunner): void {
  const output = run(
    aws(config, "cloudformation", "describe-stacks", "--stack-name", config.stateStack),
    runner,
    "State stack check",
  );
  const response = parseJson<StackResponse>(output, "the State stack outputs");
  const outputs = new Map<string, string>();
  for (const value of response.Stacks?.[0]?.Outputs ?? []) {
    if (typeof value.OutputKey === "string" && typeof value.OutputValue === "string") {
      outputs.set(value.OutputKey, value.OutputValue);
    }
  }
  const expected = new Map([
    ["CognitoUserPoolId", config.cognitoUserPoolId],
    ["CognitoUserPoolClientId", config.cognitoClientId],
    ["UsersTableName", config.usersTable],
    ["ConversationsTableName", config.conversationsTable],
    ["MessagesTableName", config.messagesTable],
    ["MediaTableName", config.mediaTable],
    ["MediaBucketName", config.bucket],
  ]);
  for (const [key, value] of expected) {
    if (outputs.get(key) !== value)
      throw new Error(`State stack output ${key} does not match runtime configuration.`);
  }
}

function createFixtureUser(
  config: LiveFixtureConfig,
  runner: CommandRunner,
  scope: FixtureScope,
  username: string,
): void {
  run(
    aws(
      config,
      "cognito-idp",
      "admin-create-user",
      "--user-pool-id",
      config.cognitoUserPoolId,
      "--username",
      username,
      "--user-attributes",
      `Name=email,Value=${username}`,
      "Name=email_verified,Value=true",
      "--message-action",
      "SUPPRESS",
    ),
    runner,
    `Create fixture user ${scope.namespace}`,
  );
}

function fixtureUserName(scope: FixtureScope, label: string): string {
  return `${scope.resourceId(label)}@fixture.invalid`;
}

function assertFixtureUser(
  config: LiveFixtureConfig,
  runner: CommandRunner,
  username: string,
): void {
  const output = run(
    aws(
      config,
      "cognito-idp",
      "admin-get-user",
      "--user-pool-id",
      config.cognitoUserPoolId,
      "--username",
      username,
    ),
    runner,
    "Read fixture user",
  );
  const user = parseJson<{
    UserAttributes?: ReadonlyArray<{ readonly Name?: unknown; readonly Value?: unknown }>;
  }>(output, "the fixture user");
  if (
    !user.UserAttributes?.some(
      (attribute) => attribute.Name === "email" && attribute.Value === username,
    )
  ) {
    throw new Error(
      "Fixture user ownership check failed: Cognito did not return the exact fixture email.",
    );
  }
}

function deleteExactUser(config: LiveFixtureConfig, runner: CommandRunner, username: string): void {
  run(
    aws(
      config,
      "cognito-idp",
      "admin-delete-user",
      "--user-pool-id",
      config.cognitoUserPoolId,
      "--username",
      username,
    ),
    runner,
    "Delete exact Cognito fixture",
  );
}

function fixtureDynamoItem(scope: FixtureScope, label: string): Record<string, { S: string }> {
  const id = scope.resourceId(label);
  return {
    fixture_run_id: { S: scope.id },
    pk: { S: id },
    sk: { S: id },
  };
}

function sentinelDynamoItem(scope: FixtureScope, label: string): Record<string, { S: string }> {
  const id = scope.resourceId(label);
  return { pk: { S: id }, sk: { S: id } };
}

function dynamoKey(item: Record<string, { S: string }>): string {
  return JSON.stringify({ pk: item.pk, sk: item.sk });
}

function putDynamoItem(
  config: LiveFixtureConfig,
  runner: CommandRunner,
  item: Record<string, { S: string }>,
): void {
  run(
    aws(
      config,
      "dynamodb",
      "put-item",
      "--table-name",
      config.usersTable,
      "--item",
      JSON.stringify(item),
      "--condition-expression",
      "attribute_not_exists(pk)",
    ),
    runner,
    "Create DynamoDB fixture",
  );
}

function getDynamoItem(
  config: LiveFixtureConfig,
  runner: CommandRunner,
  item: Record<string, { S: string }>,
): DynamoGetResponse {
  return parseJson(
    run(
      aws(
        config,
        "dynamodb",
        "get-item",
        "--table-name",
        config.usersTable,
        "--key",
        dynamoKey(item),
        "--consistent-read",
      ),
      runner,
      "Read DynamoDB fixture",
    ),
    "the DynamoDB fixture",
  );
}

function assertDynamoMarker(
  config: LiveFixtureConfig,
  runner: CommandRunner,
  item: Record<string, { S: string }>,
  marker: string,
): void {
  if (getDynamoItem(config, runner, item).Item?.fixture_run_id?.S !== marker) {
    throw new Error("DynamoDB fixture is missing its ownership marker.");
  }
}

function assertDynamoItemExists(
  config: LiveFixtureConfig,
  runner: CommandRunner,
  item: Record<string, { S: string }>,
): void {
  if (getDynamoItem(config, runner, item).Item === undefined) {
    throw new Error("DynamoDB fixture cleanup touched an unmarked sentinel.");
  }
}

function deleteMarkedDynamoItem(
  config: LiveFixtureConfig,
  runner: CommandRunner,
  item: Record<string, { S: string }>,
  marker: string,
): void {
  assertDynamoMarker(config, runner, item, marker);
  run(
    aws(
      config,
      "dynamodb",
      "delete-item",
      "--table-name",
      config.usersTable,
      "--key",
      dynamoKey(item),
      "--condition-expression",
      "fixture_run_id = :run",
      "--expression-attribute-values",
      JSON.stringify({ ":run": { S: marker } }),
    ),
    runner,
    "Delete marked DynamoDB fixture",
  );
}

function deleteExactDynamoItem(
  config: LiveFixtureConfig,
  runner: CommandRunner,
  item: Record<string, { S: string }>,
): void {
  run(
    aws(
      config,
      "dynamodb",
      "delete-item",
      "--table-name",
      config.usersTable,
      "--key",
      dynamoKey(item),
    ),
    runner,
    "Delete exact DynamoDB sentinel",
  );
}

function putFixtureObject(
  config: LiveFixtureConfig,
  runner: CommandRunner,
  key: string,
  payload: string,
  marker?: string,
): void {
  const tagging = marker === undefined ? [] : ["--tagging", `fixture-run-id=${marker}`];
  run(
    aws(
      config,
      "s3api",
      "put-object",
      "--bucket",
      config.bucket,
      "--key",
      key,
      "--body",
      payload,
      "--server-side-encryption",
      "AES256",
      ...tagging,
    ),
    runner,
    "Create S3 fixture",
  );
}

function assertObjectExists(config: LiveFixtureConfig, runner: CommandRunner, key: string): void {
  run(
    aws(config, "s3api", "head-object", "--bucket", config.bucket, "--key", key),
    runner,
    "Read S3 fixture",
  );
}

function assertObjectMarker(
  config: LiveFixtureConfig,
  runner: CommandRunner,
  key: string,
  marker: string,
): void {
  assertObjectExists(config, runner, key);
  const tags = parseJson<ObjectTaggingResponse>(
    run(
      aws(config, "s3api", "get-object-tagging", "--bucket", config.bucket, "--key", key),
      runner,
      "Read S3 fixture tag",
    ),
    "the S3 fixture tag",
  );
  if (!tags.TagSet?.some((tag) => tag.Key === "fixture-run-id" && tag.Value === marker)) {
    throw new Error("S3 fixture is missing its ownership marker.");
  }
}

function deleteMarkedObject(
  config: LiveFixtureConfig,
  runner: CommandRunner,
  key: string,
  marker: string,
): void {
  assertObjectMarker(config, runner, key, marker);
  deleteExactObject(config, runner, key);
}

function deleteExactObject(config: LiveFixtureConfig, runner: CommandRunner, key: string): void {
  run(
    aws(config, "s3api", "delete-object", "--bucket", config.bucket, "--key", key),
    runner,
    "Delete exact S3 fixture",
  );
}

if (import.meta.main) {
  try {
    for (const result of runLiveFixtureCheck(loadLiveFixtureConfig(process.env)))
      console.log(result);
  } catch (error) {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  }
}
